image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew portalInit
  command: ./gradlew tomcatStart

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java