image:
  file: .gitpod.Dockerfile

tasks:
#  - init: ./gradlew portalInit
#    command: ./gradlew tomcatStart
  - command: |
      chmod +x create-properties.sh
      mkdir portal
      ./create-properties.sh > portal/global.properties
      export PORTAL_HOME=$(pwd)/portal

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
- port: 8005
  onOpen: ignore
- port: 8887
  onOpen: ignore
- port: 38015
  onOpen: ignore
- port: 45213
  onOpen: ignore
- port: 7800
  onOpen: ignore

#vscode:
#  extensions:
#    - redhat.java