image:
  file: .gitpod.Dockerfile

tasks:
  #- init: ./gradlew portalInit
  - command: |
      mkdir portal
      export PORTAL_HOME=$(pwd)/portal
      export PORTAL_URL=$(gp url 8080)
      chmod +x *.sh
      ./create-global-properties.sh
      ./create-cas-properties.sh
      #./gradlew tomcatStart
# exposed ports
ports:
- port: 8080
  onOpen: open-preview
- port: 8005
  onOpen: ignore
- port: 8887
  onOpen: ignore
- port: 38015
  onOpen: ignore
- port: 45213
  onOpen: ignore
- port: 7800
  onOpen: ignore

#vscode:
#  extensions:
#    - redhat.java